In [2]:
import numpy as np
from qutip import *

# Hilbert uzayı boyutu
N =2

# 1. Konum Operatörü
x = position(N)
print("Konum Operatörü:\n", x)

# 2. Momentum Operatörü
p = momentum(N)
print("Momentum Operatörü:\n", p)

# 3. Yükseltme ve Düşürme Operatörleri
a = destroy(N)  # Düşürme Operatörü (Annihilation Operator)
a_dag = create(N)  # Yükseltme Operatörü (Creation Operator)
print("Düşürme Operatörü:\n", a)
print("Yükseltme Operatörü:\n", a_dag)

# 4. Sayı Operatörü
n = num(N)
print("Sayı Operatörü:\n", n)

# 5. Hamiltonyen Operatörü (Harmonik Osilatör)
omega = 1.0  # Açısal frekans
H = (p**2 / (2 * 1)) + (1 / 2) * omega**2 * (x**2)
print("Hamiltonyen Operatörü (Harmonik Osilatör):\n", H)

# 6. Pauli Matrisleri
sigma_x = sigmax()  # Pauli X Matris
sigma_y = sigmay()  # Pauli Y Matris
sigma_z = sigmaz()  # Pauli Z Matris
print("Pauli X Matrisi:\n", sigma_x)
print("Pauli Y Matrisi:\n", sigma_y)
print("Pauli Z Matrisi:\n", sigma_z)

# 7. Kimlik Operatörü
I = qeye(N)  # Kimlik Operatörü (Identity Operator)
print("Kimlik Operatörü:\n", I)

# 8. Yarıklı Operatör
b = basis(N, 0) + basis(N, 1)
proj = b * b.dag()
print("Yarıklı Operatör:\n", proj)

# 9. Projeksiyon Operatörleri
P0 = basis(2, 0) * basis(2, 0).dag()
P1 = basis(2, 1) * basis(2, 1).dag()
print("Projeksiyon Operatörü P0:\n", P0)
print("Projeksiyon Operatörü P1:\n", P1)

# 10. Dönüş Operatörü
theta = np.pi / 4
rotation_operator = qeye(2) * np.cos(theta/2) - 1j * sigmax() * np.sin(theta/2)
print("Dönüş Operatörü (π/4 açısında):\n", rotation_operator)


Konum Operatörü:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]
Momentum Operatörü:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0.+0.j         0.-0.70710678j]
 [0.+0.70710678j 0.+0.j        ]]
Düşürme Operatörü:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0. 1.]
 [0. 0.]]
Yükseltme Operatörü:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0. 0.]
 [1. 0.]]
Sayı Operatörü:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0. 0.]
 [0. 1.]]
Hamiltonyen Operatörü (Harmonik Osilatör):
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
Pauli X Matrisi:
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR,